databases:
  - name: BudgetDB
    databaseName: budgetdb_105n
    user: budgetdb_105n_user

services:
  - type: web
    name: budget
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: budgetdb_105n
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false