default: &default
  adapter: postgresql
  pool: 5
  username: postgres
  password: 654321

development:
  <<: *default
  database: budget_development 

test:
  <<: *default
  database: budget_test

production:
  <<: *default
  database: budget_production
  username: budget
  password: <%= ENV["BUDGET_DATABASE_PASSWORD"] %>